---
kind: pipeline
type: docker
name: default
steps:
  - name: rsync
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: SERVER_SECRET_KEY
      RSYNC_USER:
        from_secret: root
    settings:
      hosts:
        - monitor.webpress.vn
      port: 1080
      recursive: true
      source: .
      target: /home/monitor.webpress.vn
