---
kind: pipeline
type: docker
name: default
steps:
  - name: rsync
    image: drillster/drone-rsync
    hosts: ["monitor.webpress.vn"]
    user: root
    key:
      from_secret: SERVER_SECRET_KEY
    recursive: true
    source: .
    target: /home/monitor.webpress.vn
